// <auto-generated />
using System;
using ConsoleAppEFcore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsoleAppEFcore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241025131946_+gender")]
    partial class gender
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsoleAppEFcore.gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("genders");
                });

            modelBuilder.Entity("ConsoleAppEFcore.person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("genderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("genderId");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("ConsoleAppEFcore.person", b =>
                {
                    b.HasOne("ConsoleAppEFcore.gender", "gender")
                        .WithMany()
                        .HasForeignKey("genderId");

                    b.Navigation("gender");
                });
#pragma warning restore 612, 618
        }
    }
}
